[MINI-5532] Enable permission settings on mini app top bar
rakutentech/android-miniapp pull request #494
Opened 2022-10-25 02:26 UTC by shohiebsense

# Description
MiniApp Display -> Add permission settings icon to topbar -> navigate to permission setting
Remove permission settings in the Settings page.

## Links
[MINI-5532](https://jira.rakuten-it.com/jira/browse/MINI-5532)

# Checklist
- [x] I have read the [contributing guidelines](https://github.com/rakutentech/android-miniapp/blob/master/.github/CONTRIBUTING.md).
- [x] I have completed the [SDK Development Learning Path](https://github.com/rakutentech/android-miniapp/blob/master/.github/CONTRIBUTING.md#sdk-development-learning-path) (if submitting a feature PR)
- [x] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [x] I ran `./gradlew check` without errors

2022-10-27 05:15 UTC, laubengaier reviewed
@shohiebsense can you add some screenshots or a short video (using box) to show the result?

2022-10-27 05:55 UTC, shohiebsense commented
> @shohiebsense can you add some screenshots or a short video (using box) to show the result?

Alright updated on the description @laubengaier

2022-10-27 06:19 UTC, laubengaier approved these changes
lgtm 👍  just ui could be prettier but we can deal with that later
ios settings screen as a reference https://rak.box.com/s/b5lohut3i1avtud9v3mfgbuppcadyhyk

2022-10-27 06:19 UTC, laubengaier approved these changes

2022-10-28 05:38 UTC, rleojoseph requested changes
I guess we should not let the user to toggle on/off settings for the permissions that is set as mandatory.

2022-10-28 05:51 UTC, shohiebsense commented
afaik the case is moving the App's Permission Settings inside the Settings Page, it lists the mandatory permissions included to a MiniApp instead. 
Doesn't make it untestable for QA purposes for mandatory permissions? @rleojoseph cc: @laubengaier.  

Or do you want to keep the permission settings from the MiniApp displaying only optional permissions available while permission settings from the Settings Page display all the permissions...?

2022-10-28 05:54 UTC, munir-rakuten commented
> I guess we should not let the user to toggle on/off settings for the permissions that is set as mandatory.

but for qa purpose, isn't it good to be able to change, they can check without reinstalling the app if require permission is missing.

2022-10-28 05:58 UTC, munir-rakuten commented on testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/SettingsFragment.kt
>              switchProdVersion.isChecked = true
i think you have to add `bindings` here 
```
bindings.switchProdVersion
```

2022-10-28 06:03 UTC, shohiebsense commented
Or instead just removing completely and follows the iOS one like https://rak.app.box.com/file/1050932860895?s=b5lohut3i1avtud9v3mfgbuppcadyhyk no problem

2022-10-28 06:15 UTC, shohiebsense commented on testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/SettingsFragment.kt
>              switchProdVersion.isChecked = true
aa thanks for the heads up!

2022-10-28 06:42 UTC, rleojoseph commented
> Or instead just removing completely and follows the iOS one like https://rak.app.box.com/file/1050932860895?s=b5lohut3i1avtud9v3mfgbuppcadyhyk no problem

@shohiebsense, we should not remove it. We shouldn't provide a toggle on/off feature for the required permissions, just like iOS. 
@munir-rakuten, but we shouldn't let them to change the required permission in the first place right? So I think its not requried.

2022-10-28 06:50 UTC, shohiebsense commented
@rleojoseph ios one currently doesn't have one, or it is removed...

https://rak.box.com/s/cu5s55futfy660kjqi7r6ov5d0xvd9li

2022-10-28 06:59 UTC, rleojoseph commented
> Or instead just removing completely and follows the iOS one like https://rak.app.box.com/file/1050932860895?s=b5lohut3i1avtud9v3mfgbuppcadyhyk no problem

@shohiebsense , Permission Setting is moved to Mini App page now. You need to launch the miniapp to see/change the settings

2022-10-31 00:00 UTC, shohiebsense commented
Updated the Permission Settings with only the optional permissions toggle once accepted. @rleojoseph

2022-11-01 00:52 UTC, rleojoseph approved these changes
Looks good to me :+1:

2022-11-01 00:55 UTC, merged