[MINI-5616] Deeplink implementation update
rakutentech/android-miniapp pull request #504
Opened 2022-11-01 06:41 UTC by munir-rakuten

# Description
Update Deeplink implementation.

## Links
MINI-5616

# Checklist
- [x] I have read the [contributing guidelines](https://github.com/rakutentech/android-miniapp/blob/master/.github/CONTRIBUTING.md).
- [x] I have completed the [SDK Development Learning Path](https://github.com/rakutentech/android-miniapp/blob/master/.github/CONTRIBUTING.md#sdk-development-learning-path) (if submitting a feature PR)
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [x] I ran `./gradlew check` without errors

2022-11-02 07:43 UTC, shohiebsense approved these changes
LGTM

2022-11-02 07:46 UTC, shohiebsense commented on testapp/build.gradle
> +            resValue "string", "sslPublicKeyBackupProd", prodManifestPlaceholders.sslPublicKeyBackup
would be better if you name this sslPublicKeyProdBackup instead

2022-11-02 07:46 UTC, shohiebsense commented on testapp/build.gradle
> +            resValue "string", "sslPublicKeyBackupProd", prodManifestPlaceholders.sslPublicKeyBackup
same comment as above

2022-11-02 07:46 UTC, shohiebsense commented on testapp/build.gradle
> +            resValue "string", "sslPublicKeyBackupProd", prodManifestPlaceholders.sslPublicKeyBackup
same comment as above

2022-11-02 07:50 UTC, shohiebsense commented on testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayViewModel.kt
> +            }
Wrap into a new function instead

2022-11-02 07:50 UTC, shohiebsense commented on testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayViewModel.kt
> +            }
same suggestion as above

2022-11-02 07:51 UTC, shohiebsense requested changes
Leave some comments, other than that Looks Good, well done

2022-11-02 22:38 UTC, shohiebsense approved these changes
looks good, well done

2022-11-04 02:33 UTC, rleojoseph approved these changes
Looks good to me :+1: Just a small suggestion.

2022-11-04 02:33 UTC, rleojoseph commented on testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayViewModel.kt
> +    private val NO_MINI_APP_FOUND_ERROR = "No Mini App found for the provided Project ID."
Can we move this strings.xml file ?

2022-11-04 03:08 UTC, merged